image: Visual Studio 2017

version: 3.26.0.{build}

environment:
    matrix:
      - GEN: "Visual Studio 15 2017"
        CFG: Release
      - GEN: "Visual Studio 15 2017 Win64"
        CFG: Release

install:
    # Remove the VS Xamarin targets to reduce AppVeyor specific noise in build
    # logs.  See also http://help.appveyor.com/discussions/problems/4569
    # - del "C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
    - cd build
    - cmake -G "%GEN%" ..
    - cmake --build . --config %CFG% --clean-first

